name = "Ecosystem"
uuid = "6c5be173-c3a4-4921-a63a-7cc5134e89b2"
authors = ["kubiceko <kubicekondrej@seznam.cz>"]
version = "0.1.0"

[deps]
EcosystemCore = "3e0d8730-8ea0-4ee2-afe6-c85384c618a2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]